#!/bin/sh -e

SANITIZE="-fsanitize=address,undefined -fno-sanitize=vptr"
#SANITIZE=""

clang \
	-c \
	-g \
	-O3 \
	${SANITIZE} \
	-Wall \
	-Werror \
	-pedantic \
	-std=c11 \
	-Ideps/blibs \
	-Ideps/sokol \
	-Ideps/sokol/util \
	-Ideps/fontstash/src \
	-o sbeat.o \
	main.c

#clang \
	#-c \
	#-g \
	#-O3 \
	#${SANITIZE} \
	#-Wall \
	#-Werror \
	#-pedantic \
	#-std=c11 \
	#-Ideps/blibs \
	#-Ideps/sokol \
	#-Ideps/sokol/util \
	#-Ideps/fontstash/src \
	#-o libs.o \
	#libs.c

clang \
	-fuse-ld=mold \
	-Wl,--separate-debug-file \
	${SANITIZE} \
	-lX11 -lXi -lXcursor -lEGL -lGL \
	sbeat.o libs.o \
	-o sbeat
